### ISSUE TITLE
Replace d3-request with d3-fetch?

### ISSUE THREAD

**Issue by jleft** [d3fc/d3fc-financial-feed#17]
[d3-fetch](https://github.com/d3/d3-fetch) is still fairly new, so perhaps this is would won't be an imminent change, but something to consider in the future?

**Comment by jleft** [comment]
As of D3 [5.0.0](https://github.com/d3/d3/releases/tag/v5.0.0) (March 22, 2018), d3-request has been replaced with d3-fetch.

> D3 now uses the [Fetch API](https://fetch.spec.whatwg.org/) instead of [XMLHttpRequest](https://developer.mozilla.org/docs/Web/API/XMLHttpRequest): the [d3-request](https://github.com/d3/d3-request) module has been replaced by [d3-fetch](https://github.com/d3/d3-fetch).

_([Changes in D3 5.0](https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-50))_

Would now be a good time to replace d3-request with d3-fetch in this package? If it'd be useful, I'm happy to contribute a PR to make this change.

**Comment by chrisprice** [comment]
I think it would be a great time! A pull request would be most appreciated
👍
