### ISSUE TITLE
Poloniex.com support

### ISSUE THREAD

**Issue by sneurlax** [d3fc/d3fc-financial-feed#20]
Poloniex.com is the largest purely-cryptocurrency exchange by far and supports the exchange of many coins.  I've started working on supporting its platform at https://github.com/sneurlax/d3fc-financial-feed/tree/poloniex

Hopefully I can patch it together myself and issue a pull request soon.  There have only been a few hiccups...  I'm trying to get my BitFlux fork to work with this financial-feed fork but haven't had luck (currently waiting for ``npm install`` to finish so I can do a bit more testing)

**Comment by sneurlax** [comment]
Trying to get this working but am hitting a wall with error: ``Uncaught TypeError: Cannot read property 'historicFeed' of undefined`` ... I think this is more due to code in https://github.com/sneurlax/BitFlux/tree/poloniex , but I should have `historicFeed` for poloniex defined.

Not sure how to proceed...

**Comment by ColinEberhardt** [comment]
Thanks @sneurlax - if you need any help with adding poloneix, let me know.

One big problem you will likely encounter is that d3fc-financial-feed is part of the latest version of d3fc which supports D3v4. However, BitFlux is D3v3 so uses an older version of d3fc.

Migrating BitFlux to the latest D3v4 and d3fc is on our roadmap!

**Comment by sneurlax** [comment]
Yeah, I'm definitely having issues as mentioned above...  Although I don't think that D3v3 vs D3v4 is the issue, as I got BitFlux running just fine with the latest version of d3fc-financial-feed -- it's just adding Poloniex that's the issue.  Because the error I'm getting is so vague I'm going to have to delve into every reference to `historicfeed` (thankfully only about a dozen) and troubleshoot which reference is the problem.  My best guess at this point is that Poloniex's API responses aren't formatted correctly (or rather, I haven't parsed them correctly) and as such `historicFeed` is returning a `null` rather than the desired response...

**Comment by sneurlax** [comment]
OK, I feel like I have it *almost* there--strangely enough it wasn't any of my additions that were mucking things up, but rather a quandl bit: all I had to do was comment out this section in ``app.js`` and things cleared up:

    fcRebind.rebindAll(app, model.sources.quandl.historicFeed, fcRebind.includeMap({
        'apiKey': 'quandlApiKey'
    }));

The next hurdle was the data formatting (*ie.* ``formatPoloniexProducts``, which was failing because the returned data was an object instead of an array.  Hacked that a bit and got it parsing, at least (not sure if correctly) but now it's still making requests to gdax's API.

I really can't see why it's still calling gdax.  I'd really appreciate if you took a quick look at my code at https://github.com/sneurlax/BitFlux/tree/poloniex and include my corresponding ``d3fc-financial-feed`` from https://github.com/sneurlax/d3fc-financial-feed/tree/poloniex

**Comment by sneurlax** [comment]
No longer using bitflux / d3fc as integration with the services I require does not work.
